### ISSUE TITLE
Issue about how to set modulation frequency for CW-ToF

### ISSUE THREAD

**Issue by Hongdou68** [cmu-ci-lab/MitsubaToFRenderer#3]
Hi, I am very insteresting about your render, but when i saw the USAGE.txt, I found a problem that is how to set the modulation frequency when using CW-ToF?
I am very happy if you can help me.

**Comment by AdithyaPediredla** [comment]
Hi. thank you for you interest in the renderer and sorry for the delay in the response. 

lambda is the wavelength of the modulation waveform. lambda is in scene units. 
lambda = c/nu where nu is the modulation frequency. 

Regards,
Adithya

**Comment by Hongdou68** [comment]
Hi,Adithya:
    I met a problem when i install the mitsubaToFRender follow the INSTALL.txt. when i input the code 'scons --clean',the error appears,

![image](https://user-images.githubusercontent.com/25757403/76273027-c90f9400-62b7-11ea-935e-c4a12f313f6e.png)


Best Regards 
Hongdou Ren

**Comment by AdithyaPediredla** [comment]
Hi Hongdou Ren: 

This is surprising. Can you please run "ls" and let me know if you have a folder called "build" and a file "build/SConscript.configure"? 

Can you also please run "scons --version" and let me know what you see. 

Regards
Adithya

**Comment by Hongdou68** [comment]
Hi,Adithya:
   when i run 'ls' and 'scons --version':
![image](https://user-images.githubusercontent.com/25757403/76274633-273e7600-62bc-11ea-8a31-66f7d52b3247.png)
![image](https://user-images.githubusercontent.com/25757403/76274673-3f15fa00-62bc-11ea-94a9-1122c1171d93.png)

**Comment by AdithyaPediredla** [comment]
Thank you for the information. Can you please make sure none of the files are changed. You can do this by running "git status" and you should see "nothing to commit". If a file is changed, you can run git checkout <filename> to undo the changes. 

Sorry for asking simple things but I have never seen this problem in the past and I am also not able to replicate it on my machine. You can directly send me an email to adithya.k.pediredla@gmail.com

**Comment by Hongdou68** [comment]
Because the code was downloaded from the github using the third-party net, and according your advise, i guess there are may be some error occurs. now i directly clone the whole code  to my machine and run it again. if there are also have some questions, i will directly send email to you.
thans for your reply.
best regards 
Hongdou Ren

**Comment by AdithyaPediredla** [comment]
Sounds good. I will close the issue then. Mail me if you cannot build after directly cloning it.
