### ISSUE TITLE
Error when compiling on Ubuntu 16.04

### ISSUE THREAD

**Issue by du-dongyu** [cmu-ci-lab/MitsubaToFRenderer#4]
Dear Adithya:
I tried to compile it on my Ubuntu 16 system, however, when I execute this instruction “scons --clean”
![image](https://user-images.githubusercontent.com/58068933/76280463-e7cc5580-62cc-11ea-9a84-24ae0cbe7746.png)
 the the compilation fail due to the following error:
![image](https://user-images.githubusercontent.com/58068933/76280527-22ce8900-62cd-11ea-8256-0f802e08c58a.png)
I think it might be because I didn't install collada-dom，so I try to install it as following:
`curl -L -o ~/Downloads/collada-dom-2.4.0.tgz https://sourceforge.net/projects/collada-dom/files/latest/download
cd ~/install_dirs/
tar zxvf ~/Downloads/collada-dom-2.4.0.tgz -C ./
sudo chown -R root:root collada-dom-2.4.0/
sudo mv collada-dom-2.4.0/ /usr/local/
cd /usr/local/
sudo ln -sf collada-dom-2.4.0/ collada-dom
sudo ln -sf collada-dom-2.4.0/ collada-dom3
cd /usr/include/
sudo ln -sf /usr/local/collada-dom3 collada-dom`
This installation process mimics you installing eigen. And the result is that 
![image](https://user-images.githubusercontent.com/58068933/76280838-21ea2700-62ce-11ea-8f29-62439126ce18.png)
I thought my installation was successful, but I still get the same error as above when compiling

**Comment by AdithyaPediredla** [comment]
Hi: 

Just ignore the warning. It won't affect the installation. 

Regards,
Adithya

**Comment by du-dongyu** [comment]
Thanks for your reply～ and another question, do you think this code can run on MacOS?

**Comment by AdithyaPediredla** [comment]
One of my friends was able to build it on macOS. I have never tried it myself.

**Comment by du-dongyu** [comment]
If I ignore that warning continue with the installation, which means I execute this instruction “scons”  the the compilation fail due to the following error:
![image](https://user-images.githubusercontent.com/58068933/76281624-9625ca00-62d0-11ea-8f6f-5a79db84da40.png)

**Comment by AdithyaPediredla** [comment]
How much RAM do you have? It appears that the OS is killing the process due to a lack of memory. You can test with "free -h". You can close other processes that might be using a lot of RAM and try again.

**Comment by du-dongyu** [comment]
Thank you for your prompt reply！

The memory is really small💔. I will try to run it on another computer~


After reading your article, I learned that this renderer can be used to generate transient images in non-line-of-sight imaging system. I wonder if the simulation images in these two articles (Chia-Yin Tsai at el. 2019 CVPR & Shumian Xin at el. 2019) can also be generated with this renderer？ You know that some algorithms in NLOS consider ellipsoidal constraints during forward modeling. Because you added the ellipsoid constraint during the rendering process, will it affect the reconstruction process?
在 2020年3月10日 +0800 PM1:18，AdithyaPediredla ，写道：

**Comment by AdithyaPediredla** [comment]
The ellipsoidal constraint during the forward modeling does not affect the NLOS reconstruction process. The ellipsoidal constraint speeds up the time-gated rendering. If you are not using a time-gated camera, you can still simulate any ToF camera with this renderer. You can disable ellipsoidal connections by changing "decomposition" to transient (and enable ellipsoidal connections by setting "decomposition" to transientEllipse)

This renderer can simulate Chia Yin's paper's results (I don't think Shumian showed any simulated results, but you can simulate Fermat paths). Chia-yin used this simulator for some work, but I am not sure if it is this one. However, Chia-Yin developed a renderer that is faster than MitsubaToFRenderer for simulating NLOS (third bounce in a confocal setting). If you are only interested in NLOS and only 3rd bounce, I would suggest that you use Chia-Yin's simulator. The code is publicly available.

**Comment by du-dongyu** [comment]
It’s really awesome! And I think your work is a signiﬁcant advance  in rendering transient images！

Best regards.
Dongyu
在 2020年3月10日 +0800 PM2:37，AdithyaPediredla <notifications@github.com>，写道：

**Comment by AdithyaPediredla** [comment]
Thank you. 

I am closing this thread and if you have more questions that are not "issues" related to the renderer, please shoot me an email: adithya.k.pediredla@gmail.com. 

Regards
Adithya
