### ISSUE TITLE
NLOS render

### ISSUE THREAD

**Issue by MeLonJ10** [cmu-ci-lab/MitsubaToFRenderer#5]
Hi, it's a wonderful work to do transient rendering. But it seems that there is no command to do nlos rendering according to the USAGE.txt.

**Comment by AdithyaPediredla** [comment]
Hi MeLonJ10:

So far, NLOS imaging is performed either with an intensity camera, or transient camera, or CWAM time-of-flight camera or by wavefront sensing (using memory effect, etc.). 

Unless your sensing technique involves wave properties of light, you can always simulate your NLOS setup with this renderer. You have to design the scene based on the hardware you have or plan to build. In the manuscript accompanying this renderer (check https://imaging.cs.cmu.edu/ellipsoidal_connections/), we showed an example case to simulate NLOS imaging. 

Regards
Adithya

**Comment by MeLonJ10** [comment]
> Hi MeLonJ10:
> 
> So far, NLOS imaging is performed either with an intensity camera, or transient camera, or CWAM time-of-flight camera or by wavefront sensing (using memory effect, etc.).
> 
> Unless your sensing technique involves wave properties of light, you can always simulate your NLOS setup with this renderer. You have to design the scene based on the hardware you have or plan to build. In the manuscript accompanying this renderer (check https://imaging.cs.cmu.edu/ellipsoidal_connections/), we showed an example case to simulate NLOS imaging.
> 
> Regards
> Adithya

**Comment by MeLonJ10** [comment]
Hi Adithya,
Thank you for the reply. 
Best,
Melon

**Comment by AdithyaPediredla** [comment]
You are welcome, Melon. I am closing the issue. 

Please bother us if you have any difficulties. We recently added a docker image as well. Using the docker, you can run MitsubaToFRenderer without installation, on any OS.
