### ISSUE TITLE
Can't build gui

### ISSUE THREAD

**Issue by LZleejean** [cmu-ci-lab/MitsubaToFRenderer#6]
After `scons` command, the info as below:
```
Using configuation file "/home/lz/WorkSpace/code/MitsubaToFRenderer/config.py"
Unable to detect a Qt installation -- not building the GUI!
```

The command line mode can compile successfully. But no gui.
I tried Qt5 and Qt4  but not changed. `qmake -v` can get right info.

**Comment by AdithyaPediredla** [comment]
Sorry, the GUI for this version is broken and we do not have any plans to fix it. 

Also, you can directly use our docker image: https://hub.docker.com/repository/docker/adithyapediredla/mitsubatofrenderer and avoid installation.

**Comment by LZleejean** [comment]
Is the GUI is ok on your docker version? I compiled the command version successfully but compiled GUI version unsuccessfully.

发自我的 iPad

在 2021年5月13日，下午9:18，AdithyaPediredla ***@***.******@***.***>> 写道：


Sorry, the GUI for this version is broken and we do not have any plans to fix it.

Also, you can directly use our docker image: https://hub.docker.com/repository/docker/adithyapediredla/mitsubatofrenderer and avoid installation.

**Comment by AdithyaPediredla** [comment]
No, the GUI is broken in the docker version as well.
