### ISSUE TITLE
Installation error at the "scons" step on WSL 2 (Ubuntu 16.04)

### ISSUE THREAD

**Issue by jssy-jyggg** [cmu-ci-lab/MitsubaToFRenderer#7]
To whom it may concern,
Hello and I'm now trying to install your pack on WSL 2 (Ubuntu 16.04) following master/INSTALL.txt, encountering these problems when executing "scons --clean" (Line 34):
![image](https://user-images.githubusercontent.com/97089416/148032332-13112531-c5e8-4a59-a6aa-41fe392a93d2.png)
Here I am told to verify that g++ is installed, but I believe it has been done. I'm also attaching a screenshot of file "config.log" (see below) for potential use.
Tracing back according to lines in master/INSTALL.txt, I noticed these problems at the step of installing basic packages:
![image](https://user-images.githubusercontent.com/97089416/148032944-318d047b-42f4-4630-b2d6-5e9665d377ae.png)
Here the package "linux-headers-$(uname -r)" doesn't seem to exist, so I wonder if the package is crucial for building your project, and what I should do to tackle the situation.
I'm new to Linux myself, so a detailed explanation is highly preferred. Thank you!

Appendix: config.log
![image](https://user-images.githubusercontent.com/97089416/148034477-3a38af11-65c1-43d1-a862-16fb2aa7f3d2.png)

**Comment by AdithyaPediredla** [comment]
Hi jssy-jyggg: 

Based on the error log, you do not have I/O permissions to "/home/jyggg/proj/MitsubaToFRenderer/config.log". Using sudo (i.e. sudo scons --clean) might fix your problem. 

I have also created a docker image for MitsubaToFRenderer, which has the renderer (and all associated software and postprocessing code) preinstalled. You could use the docker image from any OS as well. I strongly suggest trying the docker image directly to avoid installing MitsubaToFRenderer from scratch. 

Regards,
Adithya

**Comment by jssy-jyggg** [comment]
Thanks for your reply, Adithya. However, the first screenshot I posted yesterday already shows the error when executing "sudo scons --clean", and the first problem is still unsolved.
And I am still confused about where the docker image (as you have mentioned) is. Do you mean "INSTALL_20.04.txt" in the current master?

**Comment by AdithyaPediredla** [comment]
Hi jssy-jyggg: 

I see. sudo is not able to find your `g++`. It might be easier to fix the IO permissions to your `/home/jyggg/proj/MitsubaToFRenderer/` folder than making `sudo` find `g++`. 
Change the ownership (`chown`) of the folder to yourself instead of root. (You can also change access to the folder with `sudo chmod -R 777 /home/jyggg/proj/MitsubaToFRenderer`)

Regarding docker, you will need signup on docker hub first ([https://login.docker.com/u/login/](https://login.docker.com/u/login/)). Then search for adithyapedireda/mitsubatofrenderer in the docker page. 

Regards,
Adithya

**Comment by jssy-jyggg** [comment]
Sorry for the late response.
The ownership change didn't seem to have any visible effect, but the docker worked out fine.
Thanks for your work and attention!
